# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$time\
$status\
$os\
$character"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold fg:#78e3bf)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[kubernetes]
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = false
style = 'fg:#c3e9fa'

[git_branch]
format = '[\[$branch(:$remote_branch)\]]($style) '
style = 'fg:#ada8f7'

[os]
disabled = true

[username]
disabled = false
show_always = false

[hostname]
disabled = false
ssh_only = true

[time]
disabled = true

[status]
disabled = true

[cmd_duration]
disabled = true

